
local cfg = {}


--- definir cada grupo com um conjunto de permissões
--- _config propriedade:
--- gtype (opcional): costumava ter apenas um grupo com o mesmo gtype por jogador (exemplo: um job gtype para ter apenas um trabalho)
--- onspawn (opcional): função (player) (chamado quando o jogador se aproxima do grupo)
--- onjoin (opcional): função (jogador) (chamado quando o jogador se junta ao grupo)
--- onleave (opcional): função (player) (chamado quando o jogador deixar o grupo)
--- (você tem acesso direto a vRP e vRPclient, o túnel ao cliente, nas chamadas de configuração)

cfg.groups = {
  ["fundadoradmin"] = {
    _config = {onspawn = function(player) vRPclient._notify(player,"You are superadmin.") end},
    "admin.deleteveh",
	"player.group.add",
    "player.group.remove",
    "admin.spawnveh",
    "admin.sprites",
    "admin.godmode",
    "admin.blips",
	"player.giveitem",
    "police.bmunjail",
    "admin.crun",
    "admin.srun",
    "player.userlist",
    "admin.tptowaypoint",
    "spikes.admin",
    "freeze.admin",
    "player.unban",
    "reviveadmin",
    "player.concertarcarro",
    "player.noclip",
    "admin.tickets",
    "admin.announce",
    "player.givedinheirosujo",
    "police.bmjail",
    "player.list",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.coords",
    "player.tptome",
    "player.tpto",
    "player.giveitem",
    "reviveplayer",
    --"mugger.mug",
	"player.givemoney",
  },
  ["superadmin"] = {
    _config = {onspawn = function(player) vRPclient._notify(player,"You are superadmin.") end},
    "admin.deleteveh",
	"player.group.add",
    "player.group.remove",
    "player.userlist",
    "freeze.admin",
    "reviveadmin",
    "player.concertarcarro",
    "player.noclip",
    "admin.tickets",
    "admin.announce",
    "police.bmjail",
    "player.list",
    "player.whitelist",
    "player.unwhitelist",
    "player.kick",
    "player.ban",
    "player.tptome",
    "reviveplayer",
  },  
  ["admin"] = {
    "admin.deleteveh",
    "reviveadmin",
    "player.tptome",
    "player.concertarcarro",
    "admin.tickets",
    "admin.announce",
    "player.kick",
    "player.ban",
  },  
  ["suporte"] = {
    "admin.deleteveh",
    "reviveadmin",
    "player.tptome",
    "admin.tickets",
    "admin.announce",
    "player.kick",
  },
  ["pamonheiro22"] = {
	"freeze.admin",
  },
  -- USER
  ["user"] = {
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"player.userlist",
    "police.store_weapons",
    "police.seizable",
    "player.fixhaircut",
    "user.paycheck",
	"mobile.pay",
	--"mobile.charge",
	"admin.deleteveh",
  },
 -- FACÇÕES
  ["CHEFE A.D.A"] = {
    _config = { gtype = "job",
        onspawn = function(player) vRPclient._notify(player,"Voce e Chefe do chefe do A.D.A") end
      },
      "police.menu",
      "police.handcuff",
      "police.check",
      "player.player_menu",
      "toggle.service",
	  "a.d.a.paycheckdinheirosujoc",
      "userr.paycheck",
      "player.store_money",
	  "traficante.defaccao",
      "player.phone",
      "player.calladmin",
      "emergency_heal",
      "police.askid",
      "campo.cocaina",
      "processador.cocaina",
      "campo.crack",
      "processador.crack",
      "police.store_weapons",
      "police.seizable",
      "arma_do_chefe.arma",
      "traficante.baseado",
      "ada.announce",
      "ada.service",
      "ada.whitelisted",
      "a.d.a.paycheck",
      "trafico_drogas",
  },
  ["CHEFE C.V"] = {
    _config = { gtype = "job",
        onspawn = function(player) vRPclient._notify(player,"Voce e Chefe do chefe do C.V") end
      },
      "police.menu",
      "police.handcuff",
      "police.check",
      "player.player_menu",
      "userr.paycheck",
      "toggle.service",
	  "mission.cocaina.information",
      "cv.cloakroom",
	  "traficante.defaccao",
      "emergency_heal",
	  "c.v.paycheckdinheirosujoc",
      "player.store_money",
      "player.phone",
      "player.calladmin",
      "police.askid",
      "campo.cocaina",
      "processador.cocaina",
      "campo.crack",
      "processador.crack",
      "police.store_weapons",
      "police.seizable",
      "arma_do_chefe.arma",
      "traficante.baseado",
      "cv.announce",
      "cv.service",
      "cv.whitelisted",
      "c.v.paycheck",
      "trafico_drogas"
  },
  ["CHEFE T.C.A"] = {
   _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e Chefe do chefe do T.C.A") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "userr.paycheck",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"traficante.defaccao",
    "campo.cocaina",
    "processador.cocaina",
    "emergency_heal",
	"t.c.a.paycheckdinheirosujoc",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "arma_do_chefe.arma",
    "traficante.baseado",
    "tca.announce",
    "tpa.service",
    "tca.whitelisted",
    "t.c.p.paycheck",
    "trafico_drogas"
  },
  ["CHEFE T.C.P"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e Chefe do chefe do T.C.P") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
	"mission.crack.information",
    "toggle.service",
	"t.c.p.paycheckdinheirosujoc",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
	"traficante.defaccao",
    "police.seizable",
    "arma_do_chefe.arma",
    "traficante.baseado",
    "tcp.announce",
    "tpc.service",
    "tcp.whitelisted",
    "t.c.p.paycheck",
    "trafico_drogas"
  },
  
  
  ["SOLDADO C.V"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e soldado do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
	"mission.cocaina.information",
    "player.store_money",
	"c.v.paycheckdinheirosujoss",
    "player.phone",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
    "userr.paycheck",
    "trafico_drogas",
    "traficante.baseado",
    "emergency_heal",
    "campo.cocaina",
	"traficante.defaccao",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["SOLDADO A.D.A"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e soldado do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "userr.paycheck",
    "player.phone",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
	"a.d.a.paycheckdinheirosujoss",
    "emergency_heal",
    "processador.cocaina",
    "campo.crack",
	"traficante.defaccao",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["SOLDADO T.C.P"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e soldado do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
	"t.c.p.paycheckdinheirosujoss",
    "player.store_money",
	"mission.crack.information",
    "player.phone",
	"traficante.defaccao",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "emergency_heal",
    "processador.crack",
    "userr.paycheck",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["SOLDADO T.C.A"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e soldado do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "police.store_weapons",
    "police.seizable",
	"t.c.a.paycheckdinheirosujoss",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
	"traficante.defaccao",
    "campo.cocaina",
    "emergency_heal",
    "processador.cocaina",
    "campo.crack",
    "userr.paycheck",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  
  
  ["BRACO DIREITO T.C.A"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e braco direito do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
	"traficante.defaccao",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
	"t.c.a.paycheckdinheirosujob",
    "trafico_drogas",
    "traficante.baseado",
    "emergency_heal",
    "campo.cocaina",
    "processador.cocaina",
    "userr.paycheck",
    "campo.crack",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["BRACO DIREITO A.D.A"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e braco direito do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "userr.paycheck",
	"traficante.defaccao",
    "player.phone",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
    "trafico_drogas",
    "emergency_heal",
    "traficante.baseado",
    "campo.cocaina",
	"a.d.a.paycheckdinheirosujob",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["BRACO DIREITO C.V"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e braco direito do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
	"mission.cocaina.information",
    "player.store_money",
	"c.v.paycheckdinheirosujob",
    "player.phone",
    "police.store_weapons",
    "userr.paycheck",
    "police.seizable",
    "police.askid",
	"traficante.defaccao",
    "trafico_drogas",
    "emergency_heal",
    "traficante.baseado",
    "campo.cocaina",
    "cv.cloakroom",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  ["BRACO DIREITO T.C.P"] = {
   _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e braco direito do trafico.") end
    },
    "police.menu",
    "police.handcuff",
    "police.check",
    "player.player_menu",
    "toggle.service",
	"mission.crack.information",
    "player.store_money",
    "userr.paycheck",
	"traficante.defaccao",
	"t.c.p.paycheckdinheirosujob",
    "player.phone",
    "police.store_weapons",
    "police.seizable",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "police.store_dinheirosujo",
    "emergency_heal",
    "player.store_dinheirosujo",
    "campo.crack",
    "processador.crack",
    "arma_do_chefe.arma",
    "braco.paycheck"
  },
  
  -- EMPREGOS
  ["MECANICO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e mecanico") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "userr.paycheck",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "vehicle.repair",
    "vehicle.replace",
    "repair.service",
    "mission.repair.1",
    "mission.repair.3",
    "mission.repair.4",
    "mission.repair.5",
    "mission.repair.2",
    "mecanico.market",
    "repair.vehicle",
    "repair.market",
    "mecanico.cloakroom",
    "repair.paycheck",
  },
  ["UBER"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e Uber.") end
    },
    "player.player_menu",
    "toggle.service",
    "userr.paycheck",
    "player.store_money",
    "player.phone",
    "emergency_heal",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "taxista.service",
    "mission.taxista.passenger",
    "uber.vehicle",
    "taxista.paycheck"
  },
  ["LIXEIRO"] = {
      _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e lixeiro.") end
      },
      "player.player_menu",
      "toggle.service",
      "emergency_heal",
      "player.store_money",
      "player.phone",
      "player.calladmin",
      "police.askid",
      "trafico_drogas",
      "userr.paycheck",
      "traficante.baseado",
      "campo.cocaina",
      "processador.cocaina",
      "campo.crack",
      "processador.crack",
      "police.store_weapons",
      "police.seizable",
      "lixeiro.vehicle",
      "mission.lixeiro.information",
      "lixeiro.paycheck",
      "lixeiro_produto",
      "lixeiro.cloakroom"
  },
  ["CARTEIRO"] = {
      _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e carteiro.") end
      },
      "player.player_menu",
      "toggle.service",
      "player.store_money",
      "player.phone",
      "emergency_heal",
      "player.calladmin",
      "police.askid",
      "trafico_drogas",
      "userr.paycheck",
      "traficante.baseado",
      "campo.cocaina",
      "processador.cocaina",
      "campo.crack",
      "processador.crack",
      "police.store_weapons",
      "police.seizable",
      "carteiro.vehicle",
      "mission.carteiro.information",
      "carteiro.paycheck",
      "correio_item",
      "carteiro.cloakroom"
  },
  ["LIMPADOR DE PISCINA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e limpador de piscina.") end
    },
    "player.player_menu",
    "emergency_heal",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "userr.paycheck",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "limpador_de_piscina.vehicle",
    "mission.limpador_de_piscina.information",
    "piscina_item",
    "limpador_de_piscina.cloakroom"
  },
  ["CIDADAO"] = {
    _config = { gtype = "job",
      onspawn = function(player) vRPclient._notify(player,"Voce e um vagabundo, va para o Departamento de trabalho.") end
      }
  },
  ["POLICIA DE FOLGA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce esta de folga") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "Rodoviaria.paycheck"
  },
  ["MOTO BOY"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e moto boy") end
     },
    "player.player_menu",
    "emergency_heal",
    "toggle.service",
    "player.store_money",
	"mission.moto_boy.entrega",
	"mission.moto_boy.entrega2",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "trafico_drogas",
    "userr.paycheck",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "mission.moto_boy.food",
    "hacker.credit_cards",
    "moto_boy.vehicle",
    "moto_boy.paycheck",
    "motoboy.cloakroom",
    "moto_boy.cocacola_pizza"
  },
  ["DELIVERY"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e moto boy") end
     },
    "player.player_menu",
    "toggle.service",
    "player.phone",
    "mission.delivery.food",
  },
  ["REPARADOR"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e moto boy") end
     },
    "player.player_menu",
    "toggle.service",
    "player.phone",
    "mission.delivery.food",
	"mission.repair.wind_turbines",
	"mission.repair.satellite_dishes",
  },
  ["PESCADOR"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e Pescador.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "emergency_heal",
    "police.store_weapons",
    "police.seizable",
    "mission.pescador.information",
    "pescador.barco",
    "pescador_peixe",
    "Pescador.paycheck"
  },
  ["MOTORISTA BANCARIO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Você é o Motorista bancario.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
	"motoristabancario.paycheck",
    "police.askid",
    "police.store_weapons",
    "emergency_heal",
    "police.seizable",
    "userr.paycheck",
    "mission.Motorista_bancario.moneybank",
    "mission.Motorista_bancario.moneybank2",
    "Motorista_bancario.vehicle",
    "Motorista_bancario.paycheck",
    "Motorista_bancario.money"
  },
    ["LEITEIRO"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e leiteiro."}) end
	},
	"player.player_menu",
	"mission.leite.food",
    "toggle.service",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.sal",
    "process.sal",
	"venda.sal",
	"bolsafamilia.paycheck",
	"harvest.vacas",
	"process.Leite",
  },
  ["GARIMPEIRO SAL"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e Garimpeiro Sal."}) end
	},
	"player.player_menu",
	"mission.sal.food",
    "toggle.service",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.sal",
    "process.sal",
	"venda.sal",
	"bolsafamilia.paycheck"
  },
  ["CATADOR DE TRIGO"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e Catador de Trigo."}) end
	},
	"player.player_menu",
	"mission.trigo.food",
    "toggle.service",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.trigo",
    "process.trigo",
	"venda.trigo",
    "bolsafamilia.paycheck"	
  },
  ["GARIMPEIRO COBRE"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e Garimpeiro Cobre."}) end
	},
	"player.player_menu",
	"mission.cobre.food",
    "toggle.service",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.Cobre",
    "process.Cobre",
	"venda.Cobre",
	"bolsafamilia.paycheck"
   },
  ["GARIMPEIRO OURO"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e Garimpeiro Ouro."}) end
	},
	"player.player_menu",
	"mission.ouro.food",
    "toggle.service",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.Ouro",
    "process.Ouro",
	"venda.Ouro",
	"bolsafamilia.paycheck"
  },
  ["GARIMPEIRO DIAMANTE"] = {
    _config = { gtype = "job",
	onspawn = function(player) vRPclient.notify(player,{"Voce e Garimpeiro Diamante."}) end
	},
    "player.player_menu",
    "toggle.service",
	"mission.diamante.food",
	"emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
	"trafico_drogas",
	"userr.paycheck",
	"traficante.baseado",
	"campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "harvest.diamante",
    "process.diamante",
	"venda.diamante",
	"bolsafamilia.paycheck"
  },
    
  -- EMPREGOS ILEGAIS
  ["FARMACEUTICO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e farmaceutico.") end
    },
    "player.player_menu",
    "toggle.service",
    "userr.paycheck",
    "emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.farmaceutico.weed",
    "hacker.credit_cards",
    "farmaceutico.market",
    "harvest.weed"
  },
  ["TRAFICANTE DE ARMA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e Traficante de arma") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "emergency_heal",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "build.gun",
    "mission.gunrunner.shipment"
  },
  ["LADRAO DE CARRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e Ladrao de carro") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "userr.paycheck",
    "trafico_drogas",
    "emergency_heal",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "hacker.credit_cards",
    "mission.carjack.vehicle"
  },
  ["MOTORISTA DE ONIBUS"] = {---motorista de onibus
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e minerador.") end
    },
    "bus.vehicle",
    "bus.cloakroom",
    "bus.paycheck",
    "minerador.pedra",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "userr.paycheck",
    "emergency_heal",
    "processador.crack"
  },
  ["HACKER"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e Hacker.") end
    },
    "player.player_menu",
    "toggle.service",
    "hacker.credit_cards",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "emergency_heal",
    "campo.cocaina",
    "userr.paycheck",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.hacker.information"
  },
  ["ADVOGADO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e advogado.") end
    },
    "player.player_menu",
    "advogado.oab",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "trafico_drogas",
    "traficante.baseado",
    "emergency_heal",
	"mission.advogado.information",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "advogado.vehicle",
    "advogado.service",
    "advogado.cloakroom",
    "emergency_heal",
    "advogado.paycheck",
    "advogado.announce"
  },
  ["TRAFICANTE DE EXTASE"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de extase.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "emergency_heal",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "userr.paycheck",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.extase.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["TRAFICANTE DE URANIO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de crack.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "emergency_heal",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "userr.paycheck",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.uranio.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["TRAFICANTE DE CRACK"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de crack.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "emergency_heal",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "userr.paycheck",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.crack.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["TRAFICANTE DE LSD"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de lsd.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "userr.paycheck",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.lsdt.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["TRAFICANTE DE COCAINA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de cocaina.") end
    },
    "player.player_menu",
    "toggle.service",
    "userr.paycheck",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "emergency_heal",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.cocaina.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["TRAFICANTE DE MACONHA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e traficante de maconha.") end
    },
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "userr.paycheck",
    "emergency_heal",
    "police.askid",
    "trafico_drogas",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
	"mission.traficante.information",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "mission.traficante.information",
    "hacker.credit_cards",
    "fogueteiro.arma"
  },
  ["VENDEDOR DE ARMA"] = {
		_config = { gtype = "job",
		onspawn = function(player) vRPclient._notify(player,"Voce  a venderdor de arma.") end
		},
    "player.player_menu",
    "toggle.service",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "emergency_heal",
    "trafico_drogas",
    "userr.paycheck",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "build.gun",
    "mission.delivery.pistol",
    "mission.delivery.shotgun",
    "mission.delivery.smg"
  },
  ["TRAFICANTE DE TARTARUGA"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient.notify(player,{"Voce e traficante de tartaruga"}) end
    },
    "player.player_menu",
    "mission.sal.food",
    "toggle.service",
    "emergency_heal",
    "player.store_money",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "trafico_drogas",
    "userr.paycheck",
    "traficante.baseado",
    "campo.cocaina",
    "processador.cocaina",
    "campo.crack",
    "processador.crack",
    "police.store_weapons",
    "police.seizable",
    "process.Tartaruga",
    "harvest.tartaruga",
    "venda.sal",
    "bolsafamilia.paycheck"
  },

  
  -- BOMBEIRO
  ["COMANDANTE BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e chefe do bombeiro") end
    },
    
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "em.announce",
    "samu.loadshop",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirocomandante.paycheck",
  },
  ["SUBCOMANDANTE BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro recruta.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirosubccomandante.paycheck",
  },
  ["CORONEL BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirocoronel.paycheck",
  },
  ["TEN CORONEL BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirotencoronel.paycheck",
  },
  ["CAPITAO BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirocapitao.paycheck",
  },
  ["PRIMEIRO SARG BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeiroprimeirosargento.paycheck",
  },
  ["CABO BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirocabo.paycheck",
  },
  ["SOLDADO BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirotensoldado.paycheck",
  },
  ["RECRUTA BOMBEIRO"] = {
    _config = { gtype = "job",
    onspawn = function(player) vRPclient._notify(player,"Voce e bombeiro.") end
    },
    "samu.loadshop",
    "em.announce",
    "player.player_menu",
    "toggle.service",
    "reviveadmin",
    "player.store_money",
    "emergency_heal",
    "player.phone",
    "player.calladmin",
    "police.askid",
    "police.store_weapons",
    "police.seizable",
    "emergency.revive",
    
    "emergency.shop",
    "emergency.service",
    "emergency.medkit",--------novo
    "emergency.cloakroom",
    "emergency.vehicle",
    "emergency.market",
    "bm.whitelisted",
    "bombeirotenrecruta.paycheck",
  },
  
  ---- POLICIA
  ["DELEGADO GERAL"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end,
    },
    "delegado.cloakroom", -- < ROUPA DA POLICIA
    "police.store_money",
    "police.darlicenca",
    "police.verificarlicenca",
    "userr.paycheck",
    "police.deletarlicenca",
    "police.easy_jail",
    "police.askid",
    "police.bmunjail",
    "police.fine",
    "police.easy_cuff",
    "police.spikes",
    "emergency_heal",
    "Police Interaction",
    "police.vehicle",
    "police.drag",
    "player.list",
    "robbery.police",
    --"police.portamalas",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "dg.paycheck"
  },
  ["CMD BOPE"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "police.cloakroom", -- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	--"police.portamalas",
	"police.checkdinheirosujo",
    "police.spikes",
    "userr.paycheck",
    "emergency_heal",
    "police.verificarlicenca",
    "Police Interaction",
    "bope.vehicle",
    "police.drag",
    "player.list",
    "robbery.police",
	"police.asklc",
	"police.takelc",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "cmdbope.paycheck",
  },
  ["SOLDADO BOPE"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "police.cloakroom", -- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	--"police.portamalas",
	"police.checkdinheirosujo",
    "police.spikes",
    "userr.paycheck",
    "emergency_heal",
    "police.verificarlicenca",
    "Police Interaction",
    "bope.vehicle",
    "police.drag",
    "player.list",
    "robbery.police",
	"police.asklc",
	"police.takelc",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "soldadobope.paycheck",
  },
  ["PRF"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "prf.cloakroom", -- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.menu_interaction",
	"police.checkdinheirosujo",
    "police.fine",
    "police.askid",
    "police.easy_cuff",
	--"police.portamalas",
    "police.spikes",
    "userr.paycheck",
	"police.asklc",
	"police.takelc",
    "emergency_heal",
    "Police Interaction",
    "police.vehicle",
    "police.drag",
    "player.list",
    "robbery.police",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "prf.paycheck"
  },
  
  ["PMRJ (Recruta)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
	"robbery.police",
    "police.fine",
    "police.easy_cuff",
    "Police Interaction",
    "police.spikes",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
	"police.checkdinheirosujo",
    "recruta.paycheck",
	--"police.portamalas",
    "player.list",
	"police.asklc",
	"police.takelc",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
  },
  ["PMRJ (Soldado)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
	"robbery.police",
    "police.fine",
    "police.easy_cuff",
    "Police Interaction",
    "police.spikes",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
	"police.checkdinheirosujo",
	--"police.portamalas",
    "player.list",
	"police.asklc",
	"police.takelc",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
	"Soldado.paycheck",
  },
  ["PMRJ (Cabo)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	--"police.portamalas",
	"police.asklc",
	"police.takelc",
	"robbery.police",
	"police.checkdinheirosujo",
    "Police Interaction",
    "police.spikes",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "cabo.paycheck",
  },
  
  ["PMRJ (Terceiro Sargento)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	"robbery.police",
    "Police Interaction",
    "police.spikes",
	"police.asklc",
	"police.takelc",
    "police.vehicle",
	"police.checkdinheirosujo",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
	--"police.portamalas",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "terceirosargento.paycheck"
  },
  ["PMRJ (Segundo Sargento)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
	"robbery.police",
	"police.asklc",
	"police.takelc",
    "police.easy_cuff",
	"police.checkdinheirosujo",
    "Police Interaction",
	--"police.portamalas",
    "police.spikes",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "segundosargento.paycheck",
  },
  ["PMRJ (Primeiro Sargento)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
	----"police.portamalas",
    "police.easy_cuff",
    "Police Interaction",
    "police.spikes",
    "police.vehicle",
	"robbery.police",
    "emergency_heal",
	"police.checkdinheirosujo",
    "police.drag",
	"police.asklc",
	"police.takelc",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
	"police.darlicenca",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "primeirosargento.paycheck",
  },
  
  ["PMRJ (Sub-Tenente)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
	----"police.portamalas",
	"police.checkdinheirosujo",
	"robbery.police",
    "police.easy_cuff",
	"police.darlicenca",
    "Police Interaction",
    "police.spikes",
    "police.vehicle",
	"police.asklc",
	"police.takelc",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "subtenente.paycheck",
  },
  ["PMRJ (Segundo Tenente)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	"robbery.police",
	"police.asklc",
	"police.checkdinheirosujo",
	"police.takelc",
    "Police Interaction",
    "police.spikes",
	----"police.portamalas",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
	"police.darlicenca",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "segundotenente.paycheck",
  },
  ["PMRJ (Primeiro Tenente)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
	--"police.portamalas",
	"police.darlicenca",
    "Police Interaction",
	"robbery.police",
    "police.spikes",
	"police.checkdinheirosujo",
	"police.asklc",
	"police.takelc",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "primeirotenente.paycheck"
  },
  
  ["PMRJ (Capitao)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
	--"police.portamalas",
    "police.bmunjail",
    "police.askid",
    "police.fine",
    "police.easy_cuff",
    "Police Interaction",
    "police.spikes",
	"police.checkdinheirosujo",
	"police.asklc",
	"police.takelc",
	"robbery.police",
    "police.vehicle",
	"police.darlicenca",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "capitao.paycheck",
  },
  ["PMRJ (Major)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
	"police.asklc",
	"police.takelc",
    "police.askid",
	"police.checkdinheirosujo",
    "police.fine",
    "police.easy_cuff",
	"police.darlicenca",
    "Police Interaction",
	"robbery.police",
    "police.spikes",
	--"police.portamalas",
    "police.vehicle",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "major.paycheck",
  },
  ["PMRJ (Tenente Coronel)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
	"robbery.police",
    "police.fine",
    "police.easy_cuff",
    "Police Interaction",
	"police.checkdinheirosujo",
    "police.spikes",
    "police.vehicle",
	--"police.portamalas",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
	"police.asklc",
	"police.takelc",
    "holdup.police",
    "police.weapons",
    "police.menu",
	"police.darlicenca",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA

    "police.loadshop",
    "cop.whitelisted",
    "tenentecoronel.paycheck",
  },
  ["PMRJ (Coronel)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
	"police.darlicenca",
	"police.checkdinheirosujo",
    "police.easy_cuff",
	"robbery.police",
    "Police Interaction",
    "police.spikes",
	--"police.portamalas",
    "police.vehicle",
	"police.asklc",
	"police.takelc",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA
    "police.loadshop",
    "cop.whitelisted",
    "coronel.paycheck",
  },
  ["PMRJ (Comandante Geral)"] = {
    _config = { gtype = "job",
    onjoin = function(player) vRPclient._setCop(player,true) end,
    onspawn = function(player) vRPclient._setCop(player,true) end,
    onleave = function(player) vRPclient._setCop(player,true) end
    },
    "Civil.cloakroom",-- < ROUPA DA POLICIA
    "police.store_money",
    "police.easy_jail",
    "police.bmunjail",
    "police.askid",
    "police.fine",
	"police.darlicenca",
	"police.checkdinheirosujo",
    "police.easy_cuff",
	"robbery.police",
    "Police Interaction",
    "police.spikes",
	--"police.portamalas",
    "police.vehicle",
	"police.asklc",
	"police.takelc",
    "emergency_heal",
    "police.drag",
    "player.list",
    "police.verificarlicenca",
    "holdup.police",
    "police.weapons",
    "police.menu",
    "police.pc",
    "police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.check",
    "police.service",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    "police.bmjail", -- PRISÃO DA DP
    "police.announce",
    "store.weapons",
    "-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
    "policiaaguia.garagem", -- GARAGEM AGUIA
    "police.weapons", -- ARMAS DA POLICIA
    "police.loadshop",
    "cop.whitelisted",
    "comandantegeral.paycheck",
  },
  
  
  -- whitelist group for police, emergency and president jobs / add player to this group and user can view the job selection / search in the map
  -- moderator=president / president is guy from the server give a player group cop ems moderator when admin is offline / sallary : $10.000
  ["cop"] = {
    "cop.whitelisted"
  },
  ["ada"] = {
    "ada.whitelisted"
  },
  ["ba"] = {
    "ba.whitelisted"
  },
  ["cv"] = {
    "cv.whitelisted"
  },
  ["bm"] = {
    "bm.whitelisted"
  },
  ["tca"] = {
    "tca.whitelisted"
  },
  ["tcp"] = {
    "tcp.whitelisted"
  }
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "fundadoradmin",
    "superadmin",
    "admin"
  }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  ["CENTRAL DE EMPREGO"] = {
    _config = {x = -268.363739013672, y = -957.255126953125, z = 31.22313880920410, blipid = 267, blipcolor = 46},
    "UBER",
	"MOTORISTA DE ONIBUS",
	"LIMPADOR DE PISCINA",
    "GARIMPEIRO SAL",
    "CATADOR DE TRIGO",
    "GARIMPEIRO COBRE",
    "GARIMPEIRO OURO",
    "GARIMPEIRO DIAMANTE",
	"LEITEIRO",
	"CARTEIRO",
	"LIXEIRO",
    "MECANICO",
    "MOTO BOY",
    "ADVOGADO",
    "MOTORISTA BANCARIO",
    "PESCADOR",
    "CIDADAO"
  },
  --[[["EMPREGO DA POLICIA"] = {
    _config = {x = -449.62930297852, y = 6010.1455078125, z = 31.71639251709, blipid = 407, blipcolor = 27, permissions = {"cop.whitelisted"} },
    "PRF",
    "CIDADAO"
  },]]
  ["EMPREGO DA PMRJ"] = { 
    _config = {x = 441.203308105469, y = -981.135131835938, z = 30.6896057128906, permissions = {"cop.whitelisted"} },
    "CMD BOPE",
	"SOLDADO BOPE",
    "DELEGADO GERAL",
	"PMRJ (Recruta)",
	"PMRJ (Soldado)",
	"PMRJ (Cabo)",
	"PMRJ (Terceiro Sargento)",
	"PMRJ (Segundo Sargento)",
	"PMRJ (Primeiro Sargento)",
	"PMRJ (Sub-Tenente)",
	"PMRJ (Segundo Tenente)",
	"PMRJ (Primeiro Tenente)",
	"PMRJ (Capitao)",
	"PMRJ (Major)",
	"PMRJ (Tenente Coronel)",
	"PMRJ (Coronel)",
	"PMRJ (Comandante Geral)",
    "CIDADAO"
  },
  ["EMPREGO BOPE"] = { 
    _config = {x = 139.24792480469, y = -763.82971191406, z = 258.15173339844, permissions = {"cop.whitelisted"} },
    "CMD BOPE",
	"SOLDADO BOPE",
    "CIDADAO",
  },
  ["EMPREGO DO BOMBEIRO"] = {
    _config = {x =  1207.8588867188, y = -1472.9903564453, z = 34.859539031982, blipid = 351, blipcolor = 3, permissions = {"bm.whitelisted"} },
	"COMANDANTE BOMBEIRO",
	"SUBCOMANDANTE BOMBEIRO",
	"CORONEL BOMBEIRO",
	"TEN CORONEL BOMBEIRO",
	"CAPITAO BOMBEIRO",
	"PRIMEIRO SARG BOMBEIRO",
	"CABO BOMBEIRO",
	"SOLDADO BOMBEIRO",
	"RECRUTA BOMBEIRO",   
    "CIDADAO"   
  },
  ["ILEGAL"] = {  ---- FAVELA SANANDREAS TCA
    _config = {x = 130.53402709961, y = -1943.1276855469, z = 20.494197845459, blipid = 407, blipcolor = 27},
    "TRAFICANTE DE MACONHA", ---- cv
    --"VENDEDOR DE ARMA",
    "HACKER",
    ----"FARMACEUTICO",
    --"TRAFICANTE DE ARMA",
    --"LADRAO DE CARRO",
    "TRAFICANTE DE LSD",
	"TRAFICANTE DE EXTASE",
    "TRAFICANTE DE COCAINA",
    "TRAFICANTE DE CRACK",
    "TRAFICANTE DE URANIO",
    --"FOQUETEIRO"  
  },
  ["ILEGAL4"] = { --- FAVELA DA BR ADA
    _config = {x = 1419.1293945313, y = -415.75665283203, z = 135.99172973633, blipid = 407, blipcolor = 27},
    "TRAFICANTE DE MACONHA",
    --"VENDEDOR DE ARMA",
    "HACKER",
    ----"FARMACEUTICO",
    --"TRAFICANTE DE ARMA",
    --"LADRAO DE CARRO",
    "TRAFICANTE DE LSD",
	"TRAFICANTE DE EXTASE",
    "TRAFICANTE DE COCAINA",
    "TRAFICANTE DE CRACK",
    "TRAFICANTE DE URANIO",
    --"FOQUETEIRO"   
  },
  ["ILEGAL 3"] = { --- FAVELA TCP
    _config = {x = -784.19067382813, y = 577.82110595703, z = 126.74500274658, blipid = 407, blipcolor = 27},
    "TRAFICANTE DE MACONHA",
    --"VENDEDOR DE ARMA",
    "HACKER",
    ----"FARMACEUTICO",
    --"TRAFICANTE DE ARMA",
    --"LADRAO DE CARRO",
    "TRAFICANTE DE LSD",
	"TRAFICANTE DE EXTASE",
    "TRAFICANTE DE COCAINA",
    "TRAFICANTE DE CRACK",
    "TRAFICANTE DE URANIO",
    --"FOQUETEIRO"  
  },
  ["TRABALHO ILEGAL"] = {
    _config = {x = 1272.4293212891, y = -1711.69140625, z = 54.77144241333, blipid = 407, blipcolor = 49},
    "TRAFICANTE DE MACONHA", ---prefeitura
    --"VENDEDOR DE ARMA",
    "HACKER",
    ----"FARMACEUTICO",
    --"TRAFICANTE DE ARMA",
    --"LADRAO DE CARRO",
    "TRAFICANTE DE LSD",
	"TRAFICANTE DE EXTASE",
    "TRAFICANTE DE COCAINA",
    "TRAFICANTE DE CRACK",
    "TRAFICANTE DE URANIO",
	"TRAFICANTE DE TARTARUGA"
  },
  ["ILEGAL 1"] = {   -- FAVELA PETROLEO CV
    _config = {x = 1674.7474365234, y = -1893.0368652344, z = 110.31902313232, blipid = 407, blipcolor = 27},
    "TRAFICANTE DE MACONHA",------cv 
    --"VENDEDOR DE ARMA",
    "HACKER",
    --"FARMACEUTICO",
    --"TRAFICANTE DE ARMA",
    --"LADRAO DE CARRO",
    "TRAFICANTE DE LSD",
	"TRAFICANTE DE EXTASE",
    "TRAFICANTE DE COCAINA",
    "TRAFICANTE DE CRACK",
    "TRAFICANTE DE URANIO",
    --"FOQUETEIRO"
  },
  ["chefe do Trafico 2"] = {
    _config = {x = 1414.6766357422, y = -413.46575927734, z = 135.99172973633, blipid = 407, blipcolor = 27, permissions = {"ada.whitelisted"} },
    "CHEFE A.D.A",
    "SOLDADO A.D.A",
    "BRACO DIREITO A.D.A"
  },
  --[[["chefe do Trafico 4"] = {
    _config = {x = 418.59060668945, y = -1811.34375, z = 32.662738800049, blipid = 407, blipcolor = 27, permissions = {"tcp.whitelisted"} },
    "CHEFE T.C.P",
    "SOLDADO T.C.P",
    "BRACO DIREITO T.C.P"
  },]]
  ["chefe do Trafico 1"] = {
    _config = {x = 129.20359802246, y = -1938.8078613281, z = 20.621507644653, blipid = 407, blipcolor = 27, permissions = {"tca.whitelisted"} },
    "CHEFE T.C.A",
    "SOLDADO T.C.A",
    "BRACO DIREITO T.C.A"
  },
  ["chefe do Trafico"] = {
    _config = {x = 1672.251953125, y = -1895.6634521484, z = 110.31903076172, blipid = 407, blipcolor = 27, permissions = {"cv.whitelisted"} },
    "CHEFE C.V",
    "SOLDADO C.V",
    "BRACO DIREITO C.V",
  }  
}

return cfg   

